import './js/sections/header';
import './js/sections/menu';
import './js/sections/home';
import './js/sections/books';
import './js/sections/getBooksCategories';
import './js/sections/getBooksByCategory';
import './js/sections/getBookById';
import './js/sections/renderBooks'
import './js/sections/all-category'
import './js/sections/getBooks';
import './js/sections/createBooksMarkup';
import './js/sections/category';
import './js/sections/shopping-list';
import './js/sections/support-ukraine';
import './js/modal';
import './js/sections/fetchApi';
